---
title: "Table 2. Studies Comparing Mean Office BP to Mean Ambulatory BP Monitoring"
author: ""
date: "November 1, 2015"
output: html_document
---


```{r global_options, include=F}
# see http://kbroman.org/knitr_knutshell/pages/Rmarkdown.html
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=F, warning=FALSE, message=FALSE, 
                      results='hide')

require(knitr)
library(reshape2)
library(ggplot2)
library(car)
library(plyr)
library(tables)
library(data.table)
library(htmlTable)

library(ztable)
options(ztable.type="html")

read_chunk('make-data.R') # call program that forms data frame
```

```{r part1} 
# Read in data, dat.1, from the make-data.R program in options
```

```{r subset1}
# subset data for table 2 and data handling

# only include those that were marked as include
dat.t2 = dat.1[dat.1$field7=="No",
                 colnames(dat.1) %in% c("field4", "field6", "field7",
                                        "field14",
                                        "field49", "field55")                                ]

# Note: daytime and nighttime abpm means were not on form.
#       Need to (add field?) go back and get that information

colnames(dat.t2) = c("author", "year", "include", 
                     "amb.office",
                       "num.meas", "mean.meas")
head(dat.t2)

dat.t2 = within(dat.t2, {
    author.year = paste(author, year, sep=", ")
    
    # number of office bp measurements
    # order of entries should be clinic|home|ambulatory|other
    # see bpsr-full-review-preview-online-form-20151101-p3.pdf, a copy of the online form

    office.mean = unlist(strsplit(as.character(dat.t2$mean.meas), split="#"))[4] # Note: assuming other is office but may not be. Will have to go back and double check the values in the papers.
    amb.mean = unlist(strsplit(as.character(dat.t2$mean.meas), split="#"))[3]
    
    # number of measurements
    office.num = unlist(strsplit(as.character(dat.t2$num.meas), split="#"))[4]
    amb.num = unlist(strsplit(as.character(dat.t2$num.meas), split="#"))[3]
    
    amb.office.yes = ifelse(amb.office=="",0,1)
})

dat.t2.sub = dat.t2[dat.t2$amb.office.yes==1,
                    colnames(dat.t2) %in% c("author.year", "office.mean",
                                            "amb.mean", "office.num", "amb.num",
                                            "amb.office.yes")]
colnames(dat.t2.sub)
dat.t2.sub = dat.t2.sub[,c(6, 3, 5, 2, 4)]
colnames(dat.t2.sub)

colnames(dat.t2.sub) = c("First author, Year",
                         "Office (n)",
                         "Office (mean)",
                         "Ambulatory (n)",
                         "Ambulatory (mean)")
dat.t2.sub

```

```{r, results='asis'}
    z=ztable(dat.t2.sub,
         zebra=2,
         zebra.color = "platinum")
  update_ztable(z, include.rownames=F)
```
