---
title: "Table 6. Studies Comparing Mean Home BP to Mean Ambulatory BP Monitoring"
author: ""
date: "November 1, 2015"
output: html_document
---

```{r global_options6, include=F, eval=FALSE}
# see http://kbroman.org/knitr_knutshell/pages/Rmarkdown.html
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=F, warning=FALSE, message=FALSE, 
                      results='hide')

require(knitr)
library(reshape2)
library(ggplot2)
library(car)
library(plyr)
library(tables)
library(data.table)
library(htmlTable)

library(ztable)
options(ztable.type="html")

#read_chunk('make-data.R') # call program that forms data frame
```

```{r part1-6} 
# Read in data, dat.1, from the make-data.R program in options
# Also make a long form data frame, dat.ts.long, for tables 2, 4, and 6
```


```{r prep6}
# prep data for Table 6
names(dat.ts.long)

compare.t6 = dat.ts.long[dat.ts.long$home.amb.yes==1 & 
                          dat.ts.long$type.descrip %in% c("amb", "home"), ]

dim(compare.t6)

dt6 = dcast(compare.t6, author.year ~ type.descrip + type.measure, value.var="value", na.rm=T)
colnames(dt6)
colnames(dt6) = c("Author, year", "Count", "Mean",
                  "Count", "Mean")

dt6
```

```{r, results='asis'}
    cgroup=c("", "Ambulatory", "Home")
    n.cgroup = c(1,2,2)
    z=ztable(dt6,
         zebra=2,
         zebra.color = "platinum")
    z=addcgroup(z,cgroup=cgroup,n.cgroup=n.cgroup)
    
    update_ztable(z, include.rownames=F, 
                  caption="Table 6. Studies Comparing Mean Home BP to Mean Ambulatory BP Monitoring")
```
