---
title: "Table 1"
output: html_document
---


```{r}
# Look at fields for Table 1: first author, year, study population,
# comparison groups, Sample size, mean age (sd), age range, % women, % AA
# ....................................

# Notes: author name field (4)
# race (23) needs cleaning
# Need to go back and see which ones are 'include' from time before
# addition of the include field (quite a few were done before that
# field was added.
names(dat.1)
levels(dat.1$exclude.update)
# only include those that were marked as include
dat.1.t1 = dat.1[dat.1$exclude=="No",
                 colnames(dat.1) %in% c("field5", "field7", 
                                         paste("field", c(11:15), sep=""),
                                         paste("field", c(19:24), sep=""),
                                        "field28")]
colnames(dat.1.t1)

colnames(dat.1.t1) = c("author", "year", 
                       "clinic.amb", "clinic.home", "home.amb", 
                       "clinic.aoffice", "aoffice.amb",  "setting",
                       "population", "mean.age",  "min.age", "max.age",
                       "female", "race")
sapply(dat.1.t1[,3:7], levels)

# 
# # make comparison fields binary
# dat.1.t1[,3:7] = apply(dat.1.t1[,3:7], 2, 
#                        function(x) {ifelse(x=="",0,1)} )

dat.1.t1[,3:7] = apply(dat.1.t1[,3:7], 2, 
                       function(x) {gsub("Comparison of ", "", x)})


dat.1.t1$comparison.groups = with(dat.1.t1,
                                  paste(clinic.amb,
                                        clinic.home,
                                        home.amb,
                                        clinic.aoffice,
                                        aoffice.amb,
                                        sep="<p>"))
dat.1.t1$comparison.groups


dat.1.t1$race
dat.1.t1$author
dat.1.t1$min.age
dat.1.t1$max.age
dat.1.t1$mean.age

names(dat.1.t1)


test = ifelse(is.na(dat.1.t1$min.age)==T,1,0)
test



dat.1.t1 = within(dat.1.t1, {
  author.year = paste(author, year, sep=", ")
  age.range = ifelse(is.na(min.age)==T,
                     paste(round(mean.age,0)), 
                     paste(round(mean.age,0), " (", 
                           round(min.age,0), ", ", 
                           round(max.age,0), ")"))
  female.2 = paste(round(female,0))
  })

names(dat.1.t1)

table1.dat = data.frame(dat.1.t1[,c(18, 14, 15, 17, 16)],
                        row.names=NULL)
colnames(table1.dat)
colnames(table1.dat) = c("First author, Year",
                         "Race/ethnicity",
                         "Comparison groups",
                         "Age (mean), age range", 
                         "Female (%)")
rownames(table1.dat)=NULL
```


```{r, results='asis', echo=FALSE}
    z=ztable(table1.dat,
         zebra=2,
         zebra.color = "platinum")
  update_ztable(z, include.rownames=F,
                caption="Table 1. Characteristics of Included Studies")
```

