---
title: "Table 9. Reproducibility"
author: ""
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

# quadas-2-2015-11-20.csv

```{r global_options9, include=F}
# see http://kbroman.org/knitr_knutshell/pages/Rmarkdown.html
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=F, warning=FALSE, message=FALSE, 
                      results='hide')

require(knitr)
library(reshape2)
library(ggplot2)
library(car)
library(plyr)
library(tables)
library(data.table)
library(htmlTable)

library(ztable)
options(ztable.type="html")
#read_chunk('make-data.R') # call program that forms data frame
```


```{r prep9}
# prep data for "Table 9. Reproducibility"
names(dat.ts.long)

compare.t9 = dat.ts.long[rep.table==1, ]
dim(compare.t9)
colnames(compare.t9)
table(compare.t9$type.measure)

compare.t9[,colnames(compare.t9) %in% c("author.year", "far.apart",
                                      "type.measure",
                                      "type.descrip",
                                      "value")]

dt9 = dcast(compare.t9, author.year + far.apart ~ type.descrip + type.measure, 
      value.var="value", na.rm=T)

class(dt9)
colnames(dt9)
colnames(dt9) = c("Author, year", 
                  "How far apart?",
                  "Count", "Mean",
                  "Count", "Mean",
                  "Count", "Mean",
                  "Count", "Mean"
                  )
```

```{r, results='asis'}

    cgroup=c("",  "Ambulatory", "Clinic", "Home", "Other")
    n.cgroup = c(2,2,2,2,2)
    z=ztable(dt9,
         zebra=2,
         zebra.color = "platinum")
    z=addcgroup(z,
                cgroup=cgroup,
                n.cgroup=n.cgroup)
    
    update_ztable(z, include.rownames=F,
                  caption="<b>Table 9. Reproducibility</b>")
```
