---
title: "Table 3. Studies Comparing Hypertension Status by Office BP Compared to Hypertension Status by Ambulatory BP Monitoring"
output: html_document
---


```{r prep3}

# office vs abpm. Table 3 in part G of form.

# NOTE: for descriptions of the columns selected below see 'variable-crosswalk.csv'

# only include those that were marked as include
dat.t3 = dat.1[dat.1$exclude=="No",
                 colnames(dat.1) %in% c("field5", "field7",
                                        "field11",
                                        "field74", "field75",
                                        "field76", "field77",
                                        "exclude")]

colnames(dat.t3)
dim(dat.t3)

# Note: daytime and nighttime abpm means were not on form.
#       Need to (add field?) go back and get that information

colnames(dat.t3) = c("author", "year", 
                     "clinic.amb",
                     "exclude",
                     "g3.table.nums", 
                     "g3.clinic.threshold.1",
                     "g3.abpm.threshold.1",
                     "g3.abpm.threshold.2")

dat.t3[!(dat.t3$clinic.amb==""),] #check values


#                         dat.t3$g3.clinic.threshold.1=="" |
#                         dat.t3$g3.abpm.threshold.1=="" |
#                         dat.t3$g3.abpm.threshold.2==""


dat.t3.sub = dat.t3[!(dat.t3$g3.table.nums==""), # only requirement to include for this table is if counts are included (will skip requirement that there are thresholds (code commented out above))
                    colnames(dat.t3) %in% c("author", "year",
                                            "g3.table.nums",
                                            "g3.clinic.threshold.1",
                                            "g3.abpm.threshold.1",
                                            "g3.abpm.threshold.2")]

dat.t3.sub = within(dat.t3.sub, {
    author.year = paste(author, year, sep=", ")
    
    # table counts
    # order of entries should be abpm=yes,office=no | abpm=yes,office=yes | abpm=no, office=no | abpm=no,office=yes
    
    # cells as follows (as in hard copy, page 6):
    #             Clinic
    # ABPM        yes | no
    #          -------|------
    #     yes  |cell1 | cell2
    #          -------|-------
    #     no   |cell3 | cell4 
    # see bpsr-full-review-preview-online-form-20151101-p4.pdf, a copy of the online form
    
    # number of measurements
  # see http://stackoverflow.com/questions/12946883/strsplit-by-row-and-distribute-results-by-column-in-data-frame
  
  num.meas.2 = ifelse(g3.table.nums=="", "|||", as.character(g3.table.nums))
  sbt = strsplit(num.meas.2, '|', fixed=TRUE)
  n <- max(sapply(sbt, length))
  l <- lapply(sbt, function(X) c(X, rep(NA, n - length(X))))
  num.2 = data.frame(t(do.call(cbind, l)))
  cell.1 = num.2$X1
  cell.2 = num.2$X2
  cell.3 = num.2$X3
  cell.4 = num.2$X4
})

colnames(dat.t3.sub)
dat.t3.sub$g3.table.nums


dat.t3.sub = dat.t3.sub[,colnames(dat.t3.sub) %in% c("author.year", 
                                                     "cell.1",
                                            "cell.2", "cell.3", "cell.4",                                               "g3.clinic.threshold.1",
                                            "g3.abpm.threshold.1",
                                            "g3.abpm.threshold.2")]


dat.t3.sub = within(dat.t3.sub, {
  cell.1 = ifelse(cell.1 == "Not reported", NA, cell.1) # make percents and n
  cell.tot = as.numeric(cell.1) + as.numeric(cell.2) + as.numeric(cell.3) + as.numeric(cell.4)
  cell.1.pct = paste0(round(100*as.numeric(cell.1)/cell.tot,1), " (", cell.1, ")")
  cell.2.pct = paste0(round(100*as.numeric(cell.2)/cell.tot,1), " (", cell.2, ")")
  cell.3.pct = paste0(round(100*as.numeric(cell.3)/cell.tot,1), " (", cell.3, ")")
  cell.4.pct = paste0(round(100*as.numeric(cell.4)/cell.tot,1), " (", cell.4, ")")
})

dat.t3.sub 

colnames(dat.t3.sub)
dim(dat.t3.sub)

dat.t3.sub = dat.t3.sub[,c(8, 1, 2, 3, 12, 11, 10, 9)]
colnames(dat.t3.sub)
colnames(dat.t3.sub) = c("Author, Year",
                         "Clinic 1",
                                  "Clinic 2",
                                  "Home 1",
                                  "abpm, no. Clinic, yes.",
                              "abpm, yes. Clinic, yes.",
                              "abpm, no. Clinic, no.", 
                              "abpm, yes. Clinic, no")


dat.t3.sub

```


```{r, results='asis'}
# NOTE: no table done for this comparison group because no numbers exist for this particular table.
    z=ztable(dat.t3.sub,
         zebra=2,
         zebra.color = "platinum",
         caption="Table 3. Studies Comparing Hypertension Status by Office BP Compared to Hypertension Status by Ambulatory BP Monitoring")

  cgroup = c("", "Thresholds", "Percent (n)")
  n.cgroup = c(1,3,4)
  
  z = addcgroup(z, 
                cgroup=cgroup, 
                n.cgroup=n.cgroup)
  
  update_ztable(z, include.rownames=F)
  
```
