---
title: "Tables 1-11"
author: ''
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 4
    theme: united
    number_sections: true
---

```{r global_options, echo=FALSE, warning=FALSE, message=FALSE,results='hide'}
# see http://kbroman.org/knitr_knutshell/pages/Rmarkdown.html
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=F, warning=FALSE, message=FALSE, 
                      results='hide')

require(knitr)
library(reshape2)
library(ggplot2)
library(car)
library(plyr)
library(tables)
library(data.table)
library(htmlTable)
library(ztable)
options(ztable.type="html")
read_chunk('make-data.R') # call program that forms data frame
```


<!--
Note: all chunks have to have unique names, if there are names.
-->


```{r part1} 
# Read in data, dat.1, from the make-data.R program in options
# Also make a long form data frame, dat.ts.long, for tables 2, 4, 6 and 9
```

---

# Table 1

```{r child = 'table1.Rmd'}
```

---

# Table 2

```{r child = 'table2.Rmd'}
```

---

# Table 4

```{r child = 'table4.Rmd'}
```

---

# Table 6

```{r child = 'table6.Rmd'}
```

---

# Table 9

```{r child = 'table9.Rmd'}
```

---

# Table 8, preliminary QUADAS descriptives.

This needs to be revised to match table 2 from doi: 10.1136/bmj.d3621

```{r child = 'table8.Rmd'}
```


---

# Table 10, summary of exclusion status, including papers that did not have an exclusion field (entered before 10/13/2015)

```{r child = 'table10.Rmd'}
```


---

# Table 11, table with reasons for exclusions

```{r child = 'table11.Rmd'}
```

